### ISSUE TITLE
-- local option with snapcheck throws exception when there is no existing snapshot file

### ISSUE THREAD

**Issue by vnitinv** [Juniper/jsnapy#208]
Hi @eeishaan Can you please check this

```
nitinkr$ jsnapy --snapcheck -f 1_iter_config_single_snapcheck.yml --local
**************************** Device: 10.2xx.1.2xx ****************************
Tests Included: test_interfaces_terse 
*************************RPC is get-interface-information*************************
ERROR, Snapshot file /etc/jsnapy/snapshots/10.209.1.218_snap_temp_get_interface_information.xml is not present in given path !!
ERROR!! AttributeError 
Complete Message: 'NoneType' object has no attribute 'xpath'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/nitinkr/Coding/PyEZ_env/jsnap_env/env/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 699, in connect
    action)
  File "/Users/nitinkr/Coding/PyEZ_env/jsnap_env/env/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 554, in get_test
    action)
  File "/Users/nitinkr/Coding/PyEZ_env/jsnap_env/env/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 414, in compare_tests
    action)
  File "/Users/nitinkr/Coding/PyEZ_env/jsnap_env/env/lib/python2.7/site-packages/jnpr/jsnapy/check.py", line 680, in generate_test_files
    action)
  File "/Users/nitinkr/Coding/PyEZ_env/jsnap_env/env/lib/python2.7/site-packages/jnpr/jsnapy/check.py", line 376, in compare_reply
    final_boolean_expr = self.expression_builder(testcases, None, **kwargs)
  File "/Users/nitinkr/Coding/PyEZ_env/jsnap_env/env/lib/python2.7/site-packages/jnpr/jsnapy/check.py", line 254, in expression_builder
    last_test_instance = kwargs['op'].test_details[kwargs['teston']][-1]
IndexError: list index out of range
```

**Comment by eeishaan** [comment]
@vnitinv There are two solutions to this problem:
1. Issue an exit(1) where we extract snapshot from file/db. As we have common snapshot for various tests, it makes sense to stop execution when there is no snapshot to run tests on.
2. If we don't want to go with option 1, we have to postpone empty snapshot detection till ETC evaluation. This way we will have accurate test reporting, which will always be empty as none of the tests would execute.

I prefer option 1 over 2. Any other point about option 2 that I may be missing?

**Comment by vnitinv** [comment]
@eeishaan  In case 1, What will happen when we have test cases with multiple rpc/commands and we miss only 1 or few of the snapshots?

**Comment by eeishaan** [comment]
With rpc/commands this issue will not arise as the rpc/commands that fail do send an error response. Hence their snapshots will not be empty. The snapshot file will be created. 
This issue will only arise when we are using --local option or --check command and the snapshot is missing.

**Comment by eeishaan** [comment]
Closing as issue is fixed
