### ISSUE TITLE
jsnap2py doesn't recognize /@ syntax

### ISSUE THREAD

**Issue by lamoni** [Juniper/jsnapy#298]
Example test:
```
        is-gt elapsed-time/@junos:seconds, 86400 {
            info Health Check - Any recently flapped BGP sessions?;
            err "BGP AS: %s, NEI: %s session flapped within the past 24 hours",peer-as,peer-address;
        }
```

Output from jsnap2py:
```
lamoni$ python jsnap2py.py -i wow.conf -o wow.yaml
Traceback (most recent call last):
  File "jsnap2py.py", line 88, in <module>
    data = test_case.parseString(content, parseAll=True).asList()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pyparsing.py", line 1041, in parseString
    raise exc
pyparsing.ParseException: Expected end of text (at char 9489), (line:314, col:9)
```

**Comment by chidanandpujar** [comment]
Hi @lamoni 
    Please check if the following syntax of config file helps,
   or please share the slax config file or refer following examples to fix the slax config file
https://github.com/Juniper/junos-snapshot-administrator/blob/master/jsnap/samples/sample.conf

```
 cat issue_298.conf 
do {
      bgp-flap-checks;
}

bgp-flap-checks {
   command show bgp neighbor;
   iterate bgp-peer {
      is-lt flap-count, 5 {
         info BGP peer flap-count < 5;
         err "BGP peer %s has %s flaps", peer-address, flap-count;
      }
   }
}

:~/ansible_release_v105_final/jsnapy/tests# jsnap2py -i issue_298.conf 
:~/ansible_release_v105_final/jsnapy/tests# cat issue_298.yml 
bgp-flap-checks:
- command: show bgp neighbor
- iterate:
    tests:
    - err: BGP peer {{post["peer-address"]}} has {{post["flap-count"]}} flaps
      info: BGP peer flap-count < 5
      is-lt: flap-count, 5
    xpath: bgp-peer
tests_include:
- bgp-flap-checks
```

Thanks
Chidanand

**Comment by chidanandpujar** [comment]
closing this issue for now.

Thanks
