### ISSUE TITLE
IOError: Could not locate logging.yml when installing jsnapy 1.3.1. from pypi

### ISSUE THREAD

**Issue by Mierdin** [Juniper/jsnapy#315]
jsnapy seems to be broken when installing from packages. Installs successfully, but gets the following error message when trying to do anything on the command line or even through the python lib:

```
~$ virtualenv venv
New python executable in /Users/mierdin/Code/Juniper/netverify-demo/venv/bin/python
Installing setuptools, pip, wheel...done.

~$ source venv/bin/activate

(venv)
~$ pip install jsnapy
Collecting jsnapy
Collecting icdiff (from jsnapy)
Collecting configparser (from jsnapy)
Collecting junos-eznc (from jsnapy)
  Using cached junos_eznc-2.1.7-py2.py3-none-any.whl
Collecting pyparsing (from jsnapy)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting colorama (from jsnapy)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting future (from jsnapy)
Collecting lxml>=3.2.4 (from junos-eznc->jsnapy)
  Downloading lxml-4.2.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.8MB)
    100% |████████████████████████████████| 8.8MB 148kB/s
Collecting pyserial (from junos-eznc->jsnapy)
  Using cached pyserial-3.4-py2.py3-none-any.whl
Collecting jinja2>=2.7.1 (from junos-eznc->jsnapy)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting scp>=0.7.0 (from junos-eznc->jsnapy)
  Using cached scp-0.10.2-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from junos-eznc->jsnapy)
Collecting six (from junos-eznc->jsnapy)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting netaddr (from junos-eznc->jsnapy)
  Using cached netaddr-0.7.19-py2.py3-none-any.whl
Collecting paramiko>=1.15.2 (from junos-eznc->jsnapy)
  Using cached paramiko-2.4.1-py2.py3-none-any.whl
Collecting ncclient>=0.5.3 (from junos-eznc->jsnapy)
Collecting MarkupSafe>=0.23 (from jinja2>=2.7.1->junos-eznc->jsnapy)
Collecting pynacl>=1.0.1 (from paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached PyNaCl-1.2.1-cp27-cp27m-macosx_10_6_intel.whl
Collecting cryptography>=1.5 (from paramiko>=1.15.2->junos-eznc->jsnapy)
  Downloading cryptography-2.2.1-cp27-cp27m-macosx_10_6_intel.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 786kB/s
Collecting bcrypt>=3.1.3 (from paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached bcrypt-3.1.4-cp27-cp27m-macosx_10_6_intel.whl
Collecting pyasn1>=0.1.7 (from paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached pyasn1-0.4.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools>0.6 in ./venv/lib/python2.7/site-packages (from ncclient>=0.5.3->junos-eznc->jsnapy)
Collecting cffi>=1.4.1 (from pynacl>=1.0.1->paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached cffi-1.11.5-cp27-cp27m-macosx_10_6_intel.whl
Collecting enum34; python_version < "3" (from cryptography>=1.5->paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography>=1.5->paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.5->paramiko>=1.15.2->junos-eznc->jsnapy)
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.5->paramiko>=1.15.2->junos-eznc->jsnapy)
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=1.15.2->junos-eznc->jsnapy)
Installing collected packages: icdiff, configparser, lxml, pyserial, MarkupSafe, jinja2, six, pycparser, cffi, pynacl, enum34, idna, asn1crypto, ipaddress, cryptography, bcrypt, pyasn1, paramiko, scp, PyYAML, netaddr, ncclient, junos-eznc, pyparsing, colorama, future, jsnapy
Successfully installed MarkupSafe-1.0 PyYAML-3.12 asn1crypto-0.24.0 bcrypt-3.1.4 cffi-1.11.5 colorama-0.3.9 configparser-3.5.0 cryptography-2.2.1 enum34-1.1.6 future-0.16.0 icdiff-1.9.1 idna-2.6 ipaddress-1.0.19 jinja2-2.10 jsnapy-1.3.1 junos-eznc-2.1.7 lxml-4.2.1 ncclient-0.5.3 netaddr-0.7.19 paramiko-2.4.1 pyasn1-0.4.2 pycparser-2.18 pynacl-1.2.1 pyparsing-2.2.0 pyserial-3.4 scp-0.10.2 six-1.11.0
>>> elapsed time 11s

(venv)
~$ jsnapy
Traceback (most recent call last):
  File "/Users/mierdin/Code/Juniper/netverify-demo/venv/bin/jsnapy", line 11, in <module>
    sys.exit(main())
  File "/Users/mierdin/Code/Juniper/netverify-demo/venv/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 1106, in main
    js = SnapAdmin()
  File "/Users/mierdin/Code/Juniper/netverify-demo/venv/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 182, in __init__
    setup_logging.setup_logging()
  File "/Users/mierdin/Code/Juniper/netverify-demo/venv/lib/python2.7/site-packages/jnpr/jsnapy/setup_logging.py", line 18, in setup_logging
    config_location = get_config_location('logging.yml')
  File "/Users/mierdin/Code/Juniper/netverify-demo/venv/lib/python2.7/site-packages/jnpr/jsnapy/__init__.py", line 43, in get_config_location
    raise FileNotFoundError('Could not locate %s' % file)
IOError: Could not locate logging.yml
```

This appears to only be present on the latest release in pypi - installing from source works fine.

**Comment by sidhujasminder** [comment]
@Mierdin please use the following command. `pip install --no-cache jsnapy`. By default it picks up from the cache, which you might have installed before, and it is unable to create the directories.
This is known issue, Please refer: https://github.com/Juniper/jsnapy/wiki/1.-Installation#major-note-for-virtualenv.

**Comment by Mierdin** [comment]
Ack, thank you.

**Comment by the-farmer** [comment]
> @Mierdin please use the following command. `pip install --no-cache jsnapy`. By default it picks up from the cache, which you might have installed before, and it is unable to create the directories. This is known issue, Please refer: https://github.com/Juniper/jsnapy/wiki/1.-Installation#major-note-for-virtualenv.

Yes it helped, thank u :D
