### ISSUE TITLE
Lot of errors :(

### ISSUE THREAD

**Issue by jsnapppy** [Juniper/jsnapy#316]
I followed the installation instruction and created the config and test file as shown in the guide. When I execute any sort of checks I am hit with lot of error messages. I don't know where to go from here.

This and a lot more.
jsnapy --snap pre -f config_check.yml 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 695, in connect
    config_data)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 387, in generate_rpc_reply
    test_files.append(yaml.load(test_file))
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)

Can someone help?

**Comment by sidhujasminder** [comment]
Please share your config file and testfiles. Also your jsnapy version(`jsnapy --version`). We will have a look at it.

**Comment by sidhujasminder** [comment]
@jsnapppy I am closing this issue for now
