### ISSUE TITLE
jsnap2py is broken in pip3.6

### ISSUE THREAD

**Issue by nskalis** [Juniper/jsnapy#327]
### Description of Issue/Question
`jsnap2py` breaks when it is installed via pip3.6

### Setup
not relevant, even the `--version` is not working

### Steps to Reproduce Issue
```
pip3.6 install jsnapy
```

### Versions Report
```
$ jsnap2py --version
  File "/usr/bin/jsnap2py", line 30
    msg = "{{%s_%s}}" % (data)
                             ^
TabError: inconsistent use of tabs and spaces in indentation
```

Could you please fix it ? And please confirm once the fix is available in pip3.6 ?

**Comment by nskalis** [comment]
when the tab issue gets resolved, then there is another issue:

```
$ jsnap2py -i jsnap.interfaces.conf -o jsnapy.interfaces.yaml
Traceback (most recent call last):
  File "/usr/bin/jsnap2py", line 125, in <module>
    if len(inputs) > 0:
TypeError: object of type 'map' has no len()
```

which is resolved by 
```
inputs = list(map(msg_change, inputs))
```
in line 23

**Comment by nskalis** [comment]
the config file produced looks like this:
```
test_show_interfaces_extensive:
- command: 'show interfaces extensive '
- iterate:
    id: './name '
    tests:
    - err: 'ERROR: the input errors for interface {{id_0}} have changed from {{pre["input-error-list/input-errors"]}}
        to {{post["input-error-list/input-errors"]}}.'
      info: Checking for input errors of interfaces ...
      no-diff-in: input-error-list/input-errors
    - err: 'ERROR: the input drops for interface {{id_0}} have changed from {{pre["input-error-list/input-drops"]}}
        to {{post["input-error-list/input-drops"]}}.'
      info: Checking for input drops of interfaces ...
      no-diff-in: input-error-list/input-drops
    - err: 'ERROR: the input discards for interface {{id_0}} have changed from {{pre["input-error-list/input-discards"]}}
        to {{post["input-error-list/input-discards"]}}.'
      info: Checking for input discards of interfaces ...
      no-diff-in: input-error-list/input-discards
    - err: 'ERROR: the output errors for interface {{id_0}} have changed from {{pre["output-error-list/output-errors"]}}
        to {{post["output-error-list/output-errors"]}}.'
      info: Checking for output errors of interfaces ...
      no-diff-in: output-error-list/output-errors
    - err: 'ERROR: the output drops for interface {{id_0}} have changed from {{pre["output-error-list/output-drops"]}}
        to {{post["output-error-list/output-drops"]}}.'
      info: Checking for output drops of interfaces ...
      no-diff-in: output-error-list/output-drops
    xpath: physical-interface
test_show_interfaces_terse:
- command: 'show interfaces terse '
- iterate:
    id: './name '
    tests:
    - err: 'ERROR: the operational status for interface {{id_0}} has changed from
        {{pre["oper-status"]}} to {{post["oper-status"]}}.'
      info: Checking PHY operational status of interfaces ...
      no-diff-in: oper-status
    - err: 'ERROR: the admin status for interface {{id_0}} has changed from {{pre["admin-status"]}}
        to {{post["admin-status"]}}.'
      info: Checking PHY admin status of interfaces ...
      no-diff-in: admin-status
    - err: 'ERROR: the interface {{id_0}} is missing.'
      info: Checking for missing interfaces at PHY level ...
      list-not-less: name
    - err: 'ERROR: the interface {{id_0}} is new.'
      info: Checking for new interfaces at PHY level ...
      list-not-more: name
    xpath: physical-interface
- iterate:
    id: './name , ./address-family/address-family-name , ./address-family/interface-address/ifa-local '
    tests:
    - err: 'ERROR: the operational status for interface {{id_0}} has changed from
        {{pre["oper-status"]}} to {{post["oper-status"]}}.'
      info: Checking LOGICAL operational status of interfaces ...
      no-diff-in: oper-status
    - err: 'ERROR: the admin status of interface {{id_0}} has changed from {{pre["admin-status"]}}
        to {{post["admin-status"]}}.'
      info: Checking LOGICAL admin status of interfaces ...
      no-diff-in: admin-status
    - err: 'ERROR: the interface {{id_0}} is missing.'
      info: Checking for missing interfaces at LOGICAL level ...
      list-not-less: name
    - err: 'ERROR: the interface {{id_0}} is new.'
      info: Checking for new interfaces at LOGICAL level ...
      list-not-more: name
    - err: 'ERROR: the address family for interface {{id_0}} has changed from {{pre["address-family/address-family-name"]}}
        to {{post["address-family/address-family-name"]}}.'
      info: Checking the address family configured in the interfaces ...
      no-diff-in: address-family/address-family-name
    - err: 'ERROR: the address family {{id_1}} is missing on interface {{id_0}}.'
      info: Checking for missing address family ...
      list-not-less: address-family/address-family-name
    - err: 'ERROR: the address family {{id_1}} has been added to the interface {{id_0}}.'
      info: Checking for new family address ...
      list-not-more: address-family/address-family-name
    - err: 'ERROR: the interface address for interface {{id_0}} has changed from {{pre["address-family/interface-address"]}}
        to {{post["address-family/interface-address"]}}.'
      info: Checking the interface address configured under the interface ...
      no-diff-in: address-family/interface-address/ifa-local
    - err: 'ERROR: the interface address {{id_2}} has gone missing on interface {{id_0}}.'
      info: Checking for missing interface address ...
      list-not-less: address-family/interface-address/ifa-local
    - err: 'ERROR: the interface address {{id_2}} has been added to the interface
        {{id_0}}.'
      info: Checking for new interface address ...
      list-not-more: address-family/interface-address/ifa-local
    xpath: physical-interface/logical-interface
tests_include:
- test_show_interfaces_terse
- test_show_interfaces_extensive
```

that causes jsnapy to fail:
```
 ERROR!! TypeError 
Complete Message:  'NoneType' object is not iterable
```

Could you please look into that and update this issue please ?
