### ISSUE TITLE
Bad error message when 'hosts' not defined in config

### ISSUE THREAD

**Issue by jtraub91** [Juniper/jsnapy#345]
### Description of Issue/Question

https://github.com/Juniper/jsnapy/blob/master/lib/jnpr/jsnapy/jsnapy.py#L853
An error will be raised indicating that the config file is not present when in fact an error is being generated due to line 846:
```
host = config_data.get('hosts')[0]
```
if 'hosts' is not defined in the config then an unanticipated error will occur since None type has no element 0

### Setup
config_file (representative)
```
tests:
  - test1.yml
  - test2.yml
  ...
```
### Steps to Reproduce Issue
Traceback:
```
>>> from jnpr.jsnapy import SnapAdmin
>>> sa = SnapAdmin()
/usr/lib/python2.7/site-packages/jnpr/jsnapy/setup_logging.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f.read())
>>> sa.connect('xxx.xxx.xxx.xxx', username, password, output_file, config_data=config_file)
>>> sa.snap(config_file, snap_tag)
/usr/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py:837: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_data = yaml.load(data)
ERROR!! config file 'NoneType' object has no attribute '__getitem__' is not present
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 992, in snap
    res = self.extract_data(data, file_name, "snap")
  File "/usr/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 853, in extract_data
    raise Exception("config file is not present ", ex)
Exception: ('config file is not present ', TypeError("'NoneType' object has no attribute '__getitem__'",))
```

### Versions Report
```
bash-4.4$ jsnapy --version
/usr/lib/python2.7/site-packages/jnpr/jsnapy/setup_logging.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f.read())
JSNAPy version: 1.3.2
```
```
bash-4.4$ python --version
Python 2.7.16
```

**Comment by rahkumar651991** [comment]
Logging is optimised for this issue. Submitted along with commit-id 9ad8375f04bf9eb2bd2283fac2260753e6f51949.

**Comment by ydnath** [comment]
https://github.com/Juniper/jsnapy/pull/347 has the fixes
