### ISSUE TITLE
Feature request: Running testfile through CLI

### ISSUE THREAD

**Issue by premeshshah** [Juniper/jsnapy#36]
Hi team  , 
is this possible to run testfile directly through CLI in JSNAPy. 
something similar to jsnap command below.
jsnap --snap before -l lab -t 100.100.100.1 -plab123 interface2.conf 

Requirement is to have the ability to provide username / password / host and testfile info via CLI only ( no need to have main config file)

currently while doing so , i am facing below error.
root@automation:/etc/jsnapy# jsnapy --snap pre -t 100.100.100.1 -l lab -p lab123  -f testfiles/test_bgp_neighbor.yml 
Connecting to device 100.100.100.1 ................
Traceback (most recent call last):
  File "/usr/local/bin/jsnapy", line 9, in <module>
    load_entry_point('jsnapy==0.1', 'console_scripts', 'jsnapy')()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 492, in main
    js.get_hosts()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 260, in get_hosts
    self.login(output_file)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 379, in login
    self.connect(hostname, username, password, output_file)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 404, in connect
    self.generate_rpc_reply(dev, output_file, hostname, username)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/jsnapy/jsnapy.py", line 273, in generate_rpc_reply
    for tfile in self.main_file['tests']:
KeyError: 'tests'

**test_bgp_neighbor.yml  is copied from example.

regards
Premesh

**Comment by vnitinv** [comment]
Fixed via #199
