### ISSUE TITLE
support nose2 framework for jsnapy tests

### ISSUE THREAD

**Issue by chidanandpujar** [Juniper/jsnapy#412]
### Description of Issue/Question
Support nose2 framework for jsnapy unit tests 
### Setup
(Please provide relevant configs, xml snapshots and related files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant. Error trace would be helpful too)
with python3.12.3 , 

https://github.com/Juniper/jsnapy/actions/runs/9030597104/job/24815206239?pr=411

======================================================================
ERROR: tests.unit.test_snap (nose2.loader.ModuleImportFailure.tests.unit.test_snap)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.unit.test_snap
Traceback (most recent call last):
  File "/home/runner/work/jsnapy/jsnapy/venv/lib/python3.12/site-packages/nose2/plugins/loader/discovery.py", line 195, in _find_tests_in_file
    module = util.module_from_name(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/jsnapy/jsnapy/venv/lib/python3.12/site-packages/nose2/util.py", line 73, in module_from_name
    __import__(name)
  File "/home/runner/work/jsnapy/jsnapy/tests/unit/test_snap.py", line 10, in <module>
    from nose.plugins.attrib import attr
  File "/home/runner/work/jsnapy/jsnapy/venv/lib/python3.12/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/runner/work/jsnapy/jsnapy/venv/lib/python3.12/site-packages/nose/core.py", line 12, in <module>
    from nose.loader import defaultTestLoader
  File "/home/runner/work/jsnapy/jsnapy/venv/lib/python3.12/site-packages/nose/loader.py", line 21, in <module>
    from nose.importer import Importer, add_path, remove_path
  File "/home/runner/work/jsnapy/jsnapy/venv/lib/python3.12/site-packages/nose/importer.py", line 12, in <module>
    from imp import find_module, load_module, acquire_lock, release_lock
ModuleNotFoundError: No module named 'imp'

### Versions Report
(Provided by running `jsnapy --version`. Please also mention python version.)

JSNAPy version: 1.3.8.dev0

**Comment by chidanandpujar** [comment]
Fixed and merged
