### ISSUE TITLE
Feature request: YAML syntax verification problem

### ISSUE THREAD

**Issue by dmontagner** [Juniper/jsnapy#80]
Hi Team,

is there a way we could detect the YAML problem seen on the test_no_diff_ERROR.yml ?

Below is the stack trace jsnapy presents. The problem with it is that it is not clear that there is a problem with the YAML syntax:

```
dmontagner@querencia ~/jnpr/jsnapy/testfiles> ../bin/jsnapy --check pre_snap1 post_snap1 -f config_check_ERROR.yml
*************************Performing test on Device: 172.27.45.132*************************
Tests Included: test_command_version
*************************Command is show interfaces terse lo**************************
----------------------Performing no-diff Test Operation----------------------
Test succeeded!! oper_status is same with value, before it is <['up']> now it is <['up']> with admin status <up>
Final result of no-diff: PASSED

Tests Included: test_command_bgp_neighbor
*************************Command is show bgp neighbor*************************
Traceback (most recent call last):
  File "../bin/jsnapy", line 9, in <module>
    load_entry_point('jsnapy==0.1', 'console_scripts', 'jsnapy')()
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 905, in main
    js.get_hosts()
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 296, in get_hosts
    self.login(output_file)
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 460, in login
    self.connect(hostname, username, password, output_file)
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 589, in connect
    action)
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 515, in get_test
    action)
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/jsnapy.py", line 351, in compare_tests
    post_snap_file)
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/check.py", line 469, in generate_test_files
    action)
  File "/Users/dmontagner/Documents/Diogo/JNPR/docs-jnpr/jsnapy/lib/python2.7/site-packages/jnpr/jsnapy/check.py", line 125, in compare_reply
    x_path = test.get('iterate').get('xpath', "no_xpath")
AttributeError: 'NoneType' object has no attribute 'get'
dmontagner@querencia ~/jnpr/jsnapy/testfiles>
```

Note: see the screenshots attached.

I wrote a simple python script to load an YAML file and print an error if there is any problem. Apparently, that syntax is perfectly fine with YAML but jsnapy is having problem with it.

Screenshots attached.
YAML files attached.

[jsnapy_yaml_issue.zip](https://github.com/Juniper/jsnapy/files/211733/jsnapy_yaml_issue.zip)

<img width="1161" alt="jsnapy_output_yaml_file_with_problem_in_the_bgp_section" src="https://cloud.githubusercontent.com/assets/4936154/14409625/229f5744-ff5c-11e5-820a-7318c6309398.png">
<img width="1215" alt="yaml_file_without_problem" src="https://cloud.githubusercontent.com/assets/4936154/14409626/22a89f70-ff5c-11e5-894f-8f085ba9b254.png">
<img width="1218" alt="yaml_file_with_problem_on_the_bgp_section" src="https://cloud.githubusercontent.com/assets/4936154/14409627/22a9d4e4-ff5c-11e5-85b1-fd21ffc4b15e.png">
<img width="921" alt="jsnapy_output_yaml_file_without_problem" src="https://cloud.githubusercontent.com/assets/4936154/14409628/22add7ec-ff5c-11e5-9e5a-1504f79e12a1.png">

**Comment by astiphout** [comment]
I was also thinking about validation after I had a few cryptic errors after mal-formatted yaml; but you could also consider something the user could solve by running yamllint package as a preprocessor:

(jsnap)astiphou-mbp:~/jsnap> yamllint chassis.yml 
chassis.yml
  1:1       warning  missing document start "---"  (document-start)
  15:81     error    line too long (117 > 80 characters)  (line-length)

Users can provide their own configuration file with rules, for example if you don't care about line-length

**Comment by ydnath** [comment]
To have an option to validate the syntax of the test file. More than just checking the yaml.

Similar/close to ansible-playbook xxx.yml --syntax-check
